name: 'Helm releaser'
description: 'Combination of a big verity of features for deploying helm chart'
author: 'devopshobbies'
inputs:
  remoteRepository:
    required: true
    description: 'The generic chart address'

  chartName:
    required: true
    description: 'The chart name to get from remote chart'

  chartVersion:
    required: true
    description: 'The version of your chart'

  context:
    required: false
    description: 'The kubernetes target context'

  kubeConfig:
    required: true
    description: 'Kubernetes config file to connect'

  releaseName:
    required: true
    description: 'The name of your release'

  valuesPath:
    required: false
    description: 'The values path to use it with generic chart'
    default: '.helm/values.yaml'

  namespace:
    required: false
    description: 'The namespace you want to deploy your services'
    default: 'default'

runs:
  using: 'node16'
  main: 'dist/index.js'
