name: 'Helm releaser'
description: 'Combination of a big verity of features for deploying helm chart'
author: 'devopshobbies'
inputs:
  genericChart:
    required: true
    description: 'The generic chart address'

  context:
    required: false
    description: 'The kubernetes target context'

  token:
    required: true
    description: 'Github token'

  kubeConfig:
    required: true
    description: 'Kubernetes config file to connect'

  releaseName:
    required: false
    description: 'The name of your release'
    default: ${{ github.repository.name }}

  valuesPath:
    required: false
    description: 'The values path to use it with generic chart'
    default: '.helm/values.yaml'

  namespace:
    required: false
    description: 'The namespace you want to deploy your services'
    default: 'default'

runs:
  using: 'node16'
  main: 'dist/index.js'
