name: 'Helm releaser'
description: 'Combination of a big verity of features for deploying helm chart'
author: 'devopshobbies'
inputs:
  genericChart:
    required: true
    description: 'The generic chart address'

  context:
    required: true
    description: 'The kubernetes target context'
    default: 'default'

  token:
    required: true
    description: 'Github token'

  kubeConfig:
    required: true
    description: 'Kubernetes config file to connect'

  valuesPath:
    required: false
    description: 'The values path to use it with generic chart'
    default: '.helm/values.yaml'

runs:
  using: 'node16'
  main: 'dist/index.js'
